
#Gameplay choices
class: Mage

#Online settings
username: ludamad

#Window settings
fullscreen: no
regen_level_on_death: yes
view_width: 1200
view_height: 720

#Font settings
font: res/fonts/Gudea-Regular.ttf

#Network settings
network_debug_mode: no
#Either 'host', 'client', or 'none'
#Shouldn't be required anymore: connection_type: client
ip: 173.246.4.128
port: 6112

#Speed settings
steps_per_draw: 1 #More is almost guaranteed to make the game faster, 1 is ideal
time_per_step: 14

#Debug settings
invincible: no #Feel like exploring ? -> yes
draw_diagnostics: no

#Control options
use_stop_actions: yes
