fullscreen: 0
regen_level_on_death: 1
view_width: 1024
view_height: 768
class: Mage
font: res/MateSC-Regular.ttf

#Either 'host', 'client', or 'none'
connection_type: client
ip: 192.168.0.24
port: 6112