fullscreen: 0
regen_level_on_death: 1
view_width: 920
view_height: 720
class: Mage
font: res/MateSC-Regular.ttf

#Either 'host', 'client', or 'none'
connection_type: none
ip: 192.168.0.24
port: 6112
steps_per_draw: 1 #More is almost guaranteed to make the game faster, 1 is ideal
time_per_step: 12
invincible: 0 #Feel like exploring ? -> 1