fullscreen: 0
regen_level_on_death: 1
view_width: 1200
view_height: 800
class: Mage
font: res/MateSC-Regular.ttf

#Either 'host', 'client', or 'none'
connection_type: client
ip: 67.204.2.45
port: 6112