fullscreen: 0
regen_level_on_death: 1
view_width: 1200
view_height: 850
class: Mage
font: res/MateSC-Regular.ttf

#Either 'host', 'client', or 'none'
connection_type: client
ip: 192.168.0.130
port: 6112