
#Gameplay choices
class: Mage

#Online settings
username: ludamad

#Window settings
fullscreen: no
regen_level_on_death: yes
view_width: 928
view_height: 700

#Font settings
font: res/fonts/Gudea-Regular.ttf

#Network settings
connection_type: host #Either 'host', 'client', or 'none'
ip: 10.15.16.160
port: 6112

#Speed settings
steps_per_draw: 1 #More is almost guaranteed to make the game faster, 1 is ideal
time_per_step: 10

#Debug settings
invincible: no #Feel like exploring ? -> yes
draw_diagnostics: no
