
#Gameplay choices
class: Mage

#Online settings
username: ludamad

#Window settingss
fullscreen: 0
regen_level_on_death: 1
view_width: 928
view_height: 700

#Font settings
font: res/fonts/Gudea-Regular.ttf

#Network settings
connection_type: none #Either 'host', 'client', or 'none'
ip: localhost
port: 6112

#Speed settings
steps_per_draw: 2 #More is almost guaranteed to make the game faster, 1 is ideal
time_per_step: 12

#Debug settings
invincible: 0 #Feel like exploring ? -> 1
draw_diagnostics: 0
