
#Gameplay choices
class: Mage

#Online settings
username: ludamad

#Window settings
fullscreen: no
regen_level_on_death: yes
view_width: 960
view_height: 720

#Gameplay preferences
autouse_health_potions: yes # can toggle in game as well
autouse_mana_potions: yes # can toggle in game as well

#Font settings
font: res/fonts/Gudea-Regular.ttf

#Network settings
ip: localhost
port: 6112

#Speed settings
steps_per_draw: 1 #More is almost guaranteed to make the game faster, 1 is ideal
time_per_step: 14

#Debug settings
network_debug_mode: yes
invincible: no #Feel like exploring ? -> yes
draw_diagnostics: no
verbose_output: no

